### ISSUE TITLE
没有办法阻止冒泡事件

### ISSUE THREAD

**Issue by ajiho** [yaohaixiao/delegate.js#2]
假如结构是这样的
```
<div id="container">
    <div class="box1">
        <span>box1</span>
        <div class="box2">
            <span>box2</span>
        </div>
    </div>
</div>
```

在box2上触发单击事件，也会触发box1的事件处理程序，jquery的on是可以通过e.stopPropagation(); 来阻止的。

**Comment by yaohaixiao** [comment]
实在是不好意思，这么久才看到你的反馈。

https://github.com/yaohaixiao/delegate.js/blob/main/stopEvent.js

使用 stopEvent(evt) 方法应该就能解决你的问题
